import yatzy as yz
import service


# The function asks the user how many players there will be and their names.
# It returns a dictionary with keys equal to their names and an empty results table generated by the function empty_table.
def user():
    while True:
        try:
            var = int(input('How many players will play: '))
            if var <= 0:
                print("Please enter a positive integer.")
                continue
            break
        except ValueError:
            print("Invalid input. Please enter a positive integer.")
    all_players = dict()
    for x in range(1, var+1):
        players = input(f'Player {x}: ')
        all_players[players] = empty_table()
    return all_players

def empty_table():
    return {
            'rolls': 0,
            'ones': '-',
            'twos': '-',
            'three': '-',
            'fours': '-',
            'fives': '-',
            'sixes': '-',
            'one pair': '-',
            'two pairs': '-',
            'three pairs': '-',
            'three of a kind': '-',
            'four of a kind':'-',
            'five of a kind': '-',
            'small straight': '-',
            'large straight': '-',
            'full straight': '-',
            'full house': '-',
            'villa': '-',
            'towel': '-',
            'chance': '-',
            'maxi yatzy': '-'
            
            }

def main():
    # The main function manages the flow of the game.
    # It initializes the players by calling the user() function.
    players = user()
    # Conducts 20 rounds of the game, corresponding to Maxi Yatzy rules.
    for r in range(20):
        # Iterates through each player.
        for p in players:
            # Prints the current score table for each player.
            for c in players:
                service.print_table(service.final_tabel_for_user(c, players[c]))
            # Displays the current round number.
            print('ROUND', r+1)
            # Calculates the number of rolls for the player.
            rolls = players[p]['rolls'] + 2 
            # Conducts a round for the player and retrieves the results.
            player, choice, var, rolls_player = yz.round({
                'player_name': p,
                'rolls': rolls
            },
            players[p])
            # Updates the player's score in the dictionary.
            players[p][choice] = var
            # Updates the number of remaining rolls for the player.
            players[p]['rolls'] = rolls_player
    # After all rounds, prints the final score tables for each player.
    for c in players:
        service.print_table(service.final_tabel_for_user(c, players[c]))

main()
